export {default as Home} from './Home.jsx'
export {default as Post} from './Post.jsx'
export {default as Login} from './Login.jsx'
export {default as Register} from './Register.jsx'
export {default as Header} from './Header.jsx'
export {default as Profile} from './Profile.jsx'